name: integration

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  integration:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install KFAC
        run: python -mpip install .

      - name: Install Dependencies
        run: python -mpip install --upgrade torchvision

      - name: Run MNIST Integration Test
        run: python tests/integration/mnist_integration_test.py
