name: style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Packages
        run: python -mpip install --upgrade setuptools pip tox virtualenv

      - name: Run Tox
        run: tox -e pre-commit
